### ISSUE TITLE
POST data (csv) to revision

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#118]
Implement POST to indicate an append to the revision. The idea is that users should post their CSV file to the appropriate controller, and we will allocate an auto incrementing ID for the change and follow a POST REDIRECT GET pattern/protocol in the API.

For now we'll only support appends. Eventually corrections and deletions will work similarly but for now appending is enough to demonstrate the purpose of the API. 

The commit route should take a commit `?message` as a query parameter that will end up as the `dcterms:description`

**Route:**
```
POST /data/:series-slug/release/:release-slug/revisions/1/changes

BODY (csv data):
W06000022,2004-01-01T00:00:00/P3Y,Female,80.7
W06000022,2004-01-01T00:00:00/P3Y,Male,78.3
```

**Append (change) is created in the database:**

```
</data/:series-slug/release/:releases-slug/revisions/:revision-id/changes/1>
    a datahost:Append,
    datahost:append "/data/life-expectancy/changesets/1/1.csv",
    datahost:appliesToRevision <./revision..>,  # note this predicate could have a better name.. 
    dcterms:description "Initial load of observations"
    .
```

**Server responds:**
`303  /data/:series-slug/release/:release-slug/revisions/1/changes/:auto-incrementing-change-id`

Note the revision will also get the inverse triple:

`</data/:series-slug/release/:releases-slug/revision/1> datahost:hasChange </data/:series-slug/release/:releases-slug/revisions/:revision-id/changes/1>`

## Validation

Uploaded data should be validated against the supplied schema. We can trivially compile our user supplied datahost schemas into malli schemas, and use them to validate the datasets, with the potential for nice error messages. Note this part of the issue could be split off until table schemas are implemented (https://github.com/Swirrl/datahost-prototypes/issues/79)

## Error on too much data

For the prototype we will enforce a limit on the append size for changes. This is because by using duratom we will be storing the CSV in memory; either as a clojure representation (e.g. `[["row1" "data"] ["row2" "data]]` or a sequence of maps representation), or as just the comma separated string.

An append size of "10,000" rows; but also with a limit of having say having a maximum of 10 appends would ensure that no dataset consumed too much memory; but sizes could appear realistic enough to accommodate some real datasets... and at least be large enough to exercise UI issues around pagination etc.

**Comment by robchamberspfc** [comment]
Example appends:

[2019.csv](https://github.com/Swirrl/datahost-prototypes/files/11819093/2019.csv)
[2020.csv](https://github.com/Swirrl/datahost-prototypes/files/11819092/2020.csv)
[2021.csv](https://github.com/Swirrl/datahost-prototypes/files/11819094/2021.csv)

**Comment by scottlowe** [comment]
Similar to how I've handled the Revision creation, rather than execute a 303 redirect after POST creation, I believe it's better to simply add a Location header that points to the 201 created resource, as per:

https://developer.mozilla.org/en-US/docs/web/http/headers/location

**Comment by kiramclean** [comment]
Issue #137 is for splitting off the validation -- can be done later and separately. For now we will take it on blind faith that data uploaded is good and consider it "valid". After #137 we can error if uploaded data does not conform to the release's schema.
