### ISSUE TITLE
GET revision contents CSV

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#119]
We currently support retrieving revision metadata via the API by requesting json from `/data/{dataset-series}/releases/{release-slug}/revisions/{revision-id}`. This issue is to provide an endpoint to support retrieving the _contents_ of a revision.

The proposed solution for the prototype is to do this via content negotiation. I.e., when json(-ld) is requested, from the above route, it will return the metadata as json, but when CSV is requested, we will return the contents of the revision as csv.

See the [W3C draft on Content Negotiation by Profile](https://www.w3.org/TR/dx-prof-conneg/) for a detailed explanation and precedent for this approach.

Route:

GET `/data/{dataset-series}/releases/{release}/revisions/{revision-id}` Accept: text/csv

Server responds with CSV of all the changes in this revision concatenated together as a single file (since they are all appends right now, there is no complicated compilation of changes required).

**Comment by scottlowe** [comment]
@kiramclean Pretty sure this is implicit and obvious, but just checking:

At this stage (prototype), all I'm concatinating is a handful of CSVs of _exactly the same format_? Simple as that?

**Comment by kiramclean** [comment]
Talked about this yesterday but just to record what we said for posterity.. yes, for now we assume all the CSVs have the same headers, so we'll just really naively strip the first row and glue them together
