### ISSUE TITLE
Add basic auth to publisher endpoints

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#153]
Add basic auth in front of all PUT/POST endpoints (only, not the GET ones) so randoms can't upload data to the alpha deployment.

We don't really need proper auth at this stage, the aim is to stop bots and random users from discovering the write API and adding data without us knowing.

**Comment by andrewmcveigh** [comment]
Is it decided whether to use NGINX or middleware?

Middleware library options I'm aware of may not be the best choice these days.

 - buddy - seems no longer maintained, at least they are looking for new maintainers
 - ring-basic-authentication - still maintained, but does slightly odd stuff to base64 encode/decode strings.

Have used both before so not like they don't work.

I guess mostly a question of whether or not we'd want basic auth in a dev/test environment without having to configure a webserver locally.

**Comment by andrewmcveigh** [comment]
Where are the user/hash(pass) pairs going to be stored?
How many users will there be?

**Comment by kiramclean** [comment]
- We only need a single user/hash pair, they can be hard-coded in the app
- We'll have only one or two users (Rob and maybe someone at ONS for now)
