### ISSUE TITLE
Remove 'commit' functionality -- Single append per revision

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#163]
This issue is to remove the ability to upload multiple files to a single revision. Ultimately each revision can have: 0 or 1 appends, 0 or 1 deletes, 0 or 1 corrections, where each is a file containing some rows that are meant to be appended/deleted/corrected.

For now we don't need to add any new functionality (i.e. do not implement deletes or corrections), just update the association between revisions and appends so that each revision can have only a single append file.

**Comment by rosado** [comment]
Just to verify: does this mean that we only want to allow 1 change per revision?

**Comment by kiramclean** [comment]
We realized calling it a “change” was confusing and not ideal so this issue is to update the code to reflect the latest update model in Rob’s presentation.

Ultimately each revision can have: 0 or 1 appends, 0 or 1 deletes, 0 or 1 corrections, where each is a file containing some rows that are meant to be appended/deleted/corrected. For now we just want to effectively rename “change” to “append” and limit support to one of those per revision.
