### ISSUE TITLE
Don't require user-supplied ID on schema creation (Auto-assign schema ID on create)

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#166]
Currently schemas are created by POST-ing to `/data/{series-slug}/releases/{release-slug}/schemas/{schema-slug}` and retrieved at `/data/{series-slug}/releases/{release-slug}/schemas`. We should not require users to supply a schema slug to create one, and since releases can only ever have one schema the URI/id for the schema can just be `/data/{series-slug}/releases/{release-slug}/schema` (these are unique).

This issue is to:
- [ ] update the create (`POST`) route for schemas to `/data/{series-slug}/releases/{release-slug}/schema` and auto-assign an ID to the schema, which should be `{base-uri}/data/{series-slug}/releases/{release-slug}/schema`
- [ ] update the GET route to the de-reference page for the schema ID, i.e. `/data/{series-slug}/releases/{release-slug}/schema`

**Comment by robchamberspfc** [comment]
Thanks @kiramclean 

Currently the `GET `for this is at `/data/{series-slug}/releases/{release-slug}/schemas`

e.g. https://ldapi-prototype.gss-data.org.uk/data/dataset-1/releases/1-1/schemas

**Couple of questions :-)**

Wanted to check this wont change? 
Should this be plural as we can only have one? 
Do we need an ID, or it this just for internal reference?

**Comment by kiramclean** [comment]
Ah good point thanks for flagging.. I think it would be conventional to stick with plural routes and get the schema using its id, so it should actually be e.g. `/data/{series-slug}/releases/{release-slug}/schemas/{schema-id}`, but we could add a route `/data/{series-slug}/releases/{release-slug}/schema` as a convenience since there will only be one schema per release..
