### ISSUE TITLE
Data seems to get pre-pended instead of appended

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#191]
Right now it looks like at least in some cases appends are concat-ed in reverse order. It appears as though tablecloth reliably concats datasets in the expected order; I think we just need to sort the revisions in order when they're fetched from the db here:

https://github.com/Swirrl/datahost-prototypes/blob/f148cccdd1765669a9bb206a47f18e81d4452676/datahost-ld-openapi/src/tpximpact/datahost/ldapi/models/revision.clj#L38

**Comment by scottlowe** [comment]
Fixed in commit: https://github.com/Swirrl/datahost-prototypes/commit/72ba0561d8280ff7f92b9d74e678922476063588
