### ISSUE TITLE
Spike corrections

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#192]
This issue is to timebox some research into how we will implement corrections. Tablecloth implements many relevant [joining algorithms](https://scicloj.github.io/tablecloth/#JoinConcat_Datasets) that are potentially useful, but we will have to decide how to implement assigning IDs to each row of a CSV and how to track them.

Questions to answer to consider this spike done:
- How will we implement assigning IDs to each row of a CSV. There are two senses in which we need IDs -- an ID for the entire row, so that we can reference the ones that change, and an ID for each observation, so that we can compare sets of rows to determine whether they've changed.
- How will we store these IDs?
  - Do we mutate the files we're given and assign the IDs in there?
  - Do we ever surface these IDs or do they remain strictly internal for our purposes?
- How to use these IDs to determine which rows of a CSV are changed, given a new CSV. Hopefully something tablecloth already implements can be useful here.

Potentially useful links/inspiration:
[Rick's qb update demo](https://swirrl.github.io/qb-update-process-prototype/)

- his implementation of assigning observation ids, based on dimension and attribute column types as described in a schema:
https://github.com/Swirrl/qb-update-process-prototype/blob/f4bf69a37c01b590c99d63d21f136c794e8db641/src/main/qbup/app.cljs#L70

**Comment by robchamberspfc** [comment]
Some thoughts from me on what this _could_ look like (covers all the types in the delta tool) - https://docs.google.com/document/d/14Au8ZEwpA0ug_F37IgWIDATptuVi3Eim_USYLERNoxE/edit

Happy to chat through

**Comment by kiramclean** [comment]
Potentially useful demo of how it should work: https://github.com/robchamberspfc/datahost-helpers/blob/main/compare-csv/readme.md

**Comment by kiramclean** [comment]
Answers to the questions above:

> - How will we implement assigning IDs to each row of a CSV. There are two senses in which we need IDs -- an ID for the entire row, so that we can reference the ones that change, and an ID for each observation, so that we can compare sets of rows to determine whether they've changed.
  - Hash the values of the dimension and attribute columns. If we want to identify observations in time we can also hash the entire row (including the measure value). See [example/scratch here](https://github.com/Swirrl/datahost-prototypes/blob/b740746f369a0d972b4749394b2b5d034110a8a2/datahost-ld-openapi/src/tpximpact/datahost/scratch/corrections.clj#L54) for implementation ideas.
    
> - How will we store these IDs?
  - In the CSV files

> - Do we mutate the files we're given and assign the IDs in there?
  - Yes, we decided this is fine since it's trivial to drop a column if necessary later. We can update the files we have to avoid storing excessive redundant files.

> - Do we ever surface these IDs or do they remain strictly internal for our purposes?
  - It is fine to return these to users (i.e. CSVs will not be round-trippable, but if that becomes a problem we will fix it then)

> How to use these IDs to determine which rows of a CSV are changed, given a new CSV. Hopefully something tablecloth already implements can be useful here.
  - See [example implementations](https://github.com/Swirrl/datahost-prototypes/blob/b740746f369a0d972b4749394b2b5d034110a8a2/datahost-ld-openapi/src/tpximpact/datahost/scratch/corrections.clj#L73) for ideas. Tablecloth implements set logic and sql-ish join logic already as column-wise operations. We can take great advantage of these.
