### ISSUE TITLE
Include corrections in downloads

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#234]
This issue is to include the data uploaded in corrections files in downloads. This should happen at ingest time like appends and deletes. 

There is [scratch code in this file](https://github.com/Swirrl/datahost-prototypes/blob/km/corrections-scratch/datahost-ld-openapi/src/tpximpact/datahost/scratch/corrections.clj#L73) with examples of possible ways to implement compiling the corrections using tablecloth.

Briefly, we need to generate an ID for each row in the CSV using the information we know from the schema, and use these to compare old and new. It may make sense to split off generating and storing these row IDs into a separate issue, depending how we go about implementing this.

After this PR users should be able to upload a file with corrections in and download the latest revision including these changes.

**Comment by rosado** [comment]
#243 took care of that, so we can close that.
