### ISSUE TITLE
Initial delta tool implementation

### ISSUE THREAD

**Issue by kiramclean** [Swirrl/datahost-prototypes#235]
The initial implementation of the delta tool is an endpoint that accepts two files and returns three files.

The inputs are two CSVs with matching headers, the outputs are three files that correspond to the additions, deletes, and corrections between the files.

The API endpoint should be separate from the current hierarchy of routes such that it could be split off eventually into a separate tool. It just doesn't make sense to write all the boilerplate for a whole new app to accommodate this one endpoint for now.

We can compare rows in the CSVs by generating IDs for each row based on the schema provided and then using comparing the two CSVs. It is ok for the resulting CSVs (outputs) to include these IDs (i.e. CSVs need not be round trippable).

There is some more explanation in the [datahost application profile draft section on it](https://docs.google.com/document/d/15QBz8zoie2tQsS3C_HvNnW99AYBtOjxpL2uJqglMYsg/edit#heading=h.tjqau4xt7r45) and an example/draft implementation of the [diffing part in this file](https://github.com/Swirrl/datahost-prototypes/blob/km/corrections-scratch/datahost-ld-openapi/src/tpximpact/datahost/scratch/delta-tool.clj).

**Comment by scottlowe** [comment]
We have decided to change the details of how this should work. The tool is no longer a standalone route and will be integrated into the changes API.

Consequently, work on the initial version has stopped. There is a rough branch of code  here: sl/delta-tool-first-cut-235. Note: that code has a hard-coded schema.
