### ISSUE TITLE
Simplify query paramaters on POST appends/retracts/corrections

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#247]
After we have merged https://github.com/Swirrl/datahost-prototypes/pull/240 we should reassess and simplify the metadata provided by query parameters on the routes to make it more consistent.

POST .../appends
POST .../retracts
POST .../corrections (following #243)

![Image](https://user-images.githubusercontent.com/17060/268938434-0407715a-83fb-446b-9d6e-1e75efd06598.png)

Firstly the other routes use query params `title`, and `description` to mean `dct:title` and `dct:description` respectively, and the `:` complicates encoding, so this is inconsistent with our conventions elsewhere.

Secondly I think we can probably remove the format field, and mandate for now (in the routes doc string) that we're assuming the use of RFC4180 in UTF-8 here.  For full generality we'd need all the options of the CSVW dialect, so I think the field here isn't sufficient as it stands anyway.

**Comment by rosado** [comment]
OK, this is half done - the query params were not supposed to of the format 'foo:bar', they just happened to work after some recent changes. 

As for the format: we could pull the format of the uploaded type from the request headers (`content-type`).

**Comment by RickMoynihan** [comment]
Yeah totally agree 👍

**Comment by RickMoynihan** [comment]
Fixed in #249
