### ISSUE TITLE
Allow more than one change per revision

### ISSUE THREAD

**Issue by RicSwirrl** [Swirrl/datahost-prototypes#253]
To support the demo UI, we need to allow multiple changes per revision.

Ideally, we'd only allow at most one of each _type_ of changeset per revision (e.g. no more than one set of appends).

 e.g. to support a structure like below. 

But if this is tricky to do quickly, we could for now just not make (say) more than one set of appends per revision in our test data (that we use for our demo).

```
Rev1:
	c1: append
	c2: retract
	c3: delete
Rev2:
	c1: append
Rev3:
	c1: correction
```

**Comment by RickMoynihan** [comment]
To be clear this should be merged and deployed with the ONS branch https://github.com/Swirrl/datahost-prototypes/issues/254 and need not occur on the main branch as it may end up being reverted.

**Comment by rosado** [comment]
Fixed by https://github.com/Swirrl/datahost-prototypes/pull/258

**Comment by rosado** [comment]
Add hurl scripts for the issue: 6102196c06f1e7b7f57ea1eba8d3dce78e48e361
