### ISSUE TITLE
Dockerise consumer-wireframes app

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#318]
Feel free to deliver as two PRs

1. Dockerise consumer-wireframes app
2. Migrate from netlify deployment to a docker based deployment of the app on GCP
3. Start up wireframe app in CI and run a simple hurl smoke test against catalog page

Either 1 & 2 together, or 1 & 3

**Comment by xdrcft8000** [comment]
completed 1 2 and 3(partially):
https://github.com/Swirrl/datahost-prototypes/pull/319

**Comment by rosado** [comment]
@RickMoynihan does 1. mean just putting the _a_ docker image of the frontend manually and use that or building and deploying to Container Registry in CI?

**Comment by xdrcft8000** [comment]
https://github.com/Swirrl/datahost-prototypes/pull/319
