### ISSUE TITLE
Fix bugs on the prototype UI

### ISSUE THREAD

**Issue by xdrcft8000** [Swirrl/datahost-prototypes#322]
Current UI url: https://dluhc-pmd5-prototype-ui.publishmydata.com

Current bugs:

- [X] undefined displaying instead series info on release page: http://34.36.36.244:8080/datasets/dataset-series/dataset-release/?/data/second-series-on-GCP/release/release-1 (This happened due to the default domain being set as gss-data, so the "inSeries" field in the metadata is wrong)
- [x] No table schema printed on release page. (link as above)
- [x] Revision page does not display breadcrumb menu or any information about series/revision: http://34.36.36.244:8080/datasets/dataset-series/dataset-release/dataset-revision/?/data/second-series-on-GCP/release/release-1/revision/1
- [X] Would be nice if the date displayed in a human readable format first and the time stamp in brackets after
- [x] License isn't showing for series even when included in params

a basic hurl script to upload a dataset can be found here: https://github.com/Swirrl/datahost-prototypes/blob/tr/fix-ui/gcptest.hurl

example usage form Datahost-prototype dir: 

```
hurl gcptest.hurl --variable series=fifthseries --variable host_name=35.242.161.174 --variable scheme=http
```

**Comment by RickMoynihan** [comment]
> (This happened due to the default domain being set as gss-data, so the "inSeries" field in the metadata is wrong)

I'm assuming [you mean this](https://github.com/Swirrl/datahost-prototypes/blob/6e675ebc3053719526d1e1670930f5cbdc4fc60e/datahost-ld-openapi/env/docker/resources/ldapi/env.edn#L7), it seems we might need to change that to be configured by a `#env` tagged reader:

```clojure
{,,,
:tpximpact.datahost.system-uris/uris {:rdf-base-uri #uri #env "LD_API_RDF_BASE_URI"}
,,,}
```

**Comment by xdrcft8000** [comment]
sounds good, what else needs to be changed if I add this env variable? I'm assuming it will break something if the env isn't set, so I would probably need to set it on terraform right? or include a default somehow?

**Comment by xdrcft8000** [comment]
Aside from change the env variable for ldapi - the bugs addressed have all been addressed: https://github.com/Swirrl/datahost-prototypes/pull/323#issuecomment-1895985944
