### ISSUE TITLE
Redirect should be a 302 not a 308

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#335]
`308` means a permanent redirect, which would imply consumers should no longer access the resource by its release URL.

This should be a 302 instead because for some use cases e.g. getting "the latest data" we expect consumers to access the URL via the release.

https://github.com/Swirrl/datahost-prototypes/blob/c5618aabeb4f7af163f30df310ee5c69a2122643/datahost-ld-openapi/src/tpximpact/datahost/ldapi/routes/middleware.clj#L233

**Comment by scottlowe** [comment]
Issue was closed by this commit: https://github.com/Swirrl/datahost-prototypes/pull/337/commits/273127f31c6a10e1d8662d1897477367f32c6908
