### ISSUE TITLE
dh:hasRelease gives an array if there are multiple revisions but a scalar with a single change

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#363]
See also #348, #359

**Comment by kjoshi** [comment]
Not sure if I'm just looking in the wrong places, but I can't find `dh:hasRelease` being used anywhere at the moment (you've mentioned wanting to start using it in issue #369). So I think this issue can be closed?

**Comment by RickMoynihan** [comment]
Ahh yes sorry closing this it's a dupe of #369 which better describes it... 

I copied the title as it's analogous to #359 though the difference is that we don't currently have has:Relase on series.
