### ISSUE TITLE
Improve revisions list table

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#386]
- Include revision number in table
- Remove display of description
- Display title of revision in table
- Link to delta download for revision (could be a small download button)
- Link to full download for revision (could be a small download button)

**Comment by xdrcft8000** [comment]
for review

![Image](https://github.com/Swirrl/datahost-prototypes/assets/127414270/ad170cf3-6e52-4579-84a6-a53ba416c969)
