### ISSUE TITLE
Fix try API button to work on revision page

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#387]
e.g. here: 

https://dluhc-pmd5-prototype-ui.publishmydata.com/datasets/dataset-series/dataset-release/?series=English-Indices-of-Deprivation&release=2019

Clicking the button gives an empty body.

![Image](https://github.com/Swirrl/datahost-prototypes/assets/17060/8c83c413-43ec-4b35-8abd-614e855c41b6)

**Comment by xdrcft8000** [comment]
When accessing a series or revision in browser you get a JSON response of the series/revision. e.g.
https://dluhc-pmd5-prototype.publishmydata.com/data/English-Indices-of-Deprivation
https://dluhc-pmd5-prototype.publishmydata.com/data/English-Indices-of-Deprivation/release/2019/revision/1


Accessing a release doesn't do that:
https://dluhc-pmd5-prototype.publishmydata.com/data/English-Indices-of-Deprivation/release/2019 - returns nothing

Adding a slash takes you to the latest revision
https://dluhc-pmd5-prototype.publishmydata.com/data/English-Indices-of-Deprivation/release/2019/

For now I've just used a .json extension to make the button work:
https://dluhc-pmd5-prototype.publishmydata.com/data/English-Indices-of-Deprivation/release/2019.json - returns json of the release as expected for the button.

But that doesn't feel consistent with series and revision so I thought I'd mention it - not sure what the intended behaviour is
