### ISSUE TITLE
New routes

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#52]
Add routes for:

- `PUT /data/:series/:release`
- `GET /data/:series/:release`
- `POST /data/:series/:release/revision`
- ...

- `POST /data/:series/:release/schema`

**Comment by kiramclean** [comment]
This is old, right? Superseded by #75, #79 iiuc?

**Comment by RickMoynihan** [comment]
Good spot!  Closing 🙇
