### ISSUE TITLE
Sync triples from documents into triple store

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#55]
- remove duratom
- (de)serialise json-ld as RDF on the fly, storing everything in only the triplestore

-------------------

The documents are currently stored in duratom which maintains the same interface as a clojure atom.

All clojure reference types along with the `duratom` library we're using support [`add-watch`](https://clojuredocs.org/clojure.core/add-watch).  

So an easy way to sync and serialise changes in the documents to RDF is by calling our `ednld->rdf` on the document and writing the triples to the native-store triplestore through a watcher added to the `duratom`.

If the triplestore write fails, we should retract the changes to the duratom too.

## Is this safe?

Short answer yes.

Medium answer: Yes, safe enough for now (eventually consistent)... though in a production system we would additional consistency checks to ensure eventual consistency, and a method for handling partial failure.  The duratom will witness changes before the triple store, so we need to assume that; but as writes to the `duratom` and triplestore are synchronous to the initial blocking request, providing a user blocks on their requests future requests should appear consistent.

Long answer for people who spotted one potential gotcha:

The docstring for `add-watch` warns that the watcher may be called from multiple threads; and additionally watches on clojure atoms don't [guarantee order semantics](https://groups.google.com/g/clojure/c/RI1Pq3E3188/m/YyqyGq36f1oJ) which would be bad as there'd be a risk of the databases containing different states.

However I have looked and it seems that [duratom does protect against this](https://github.com/jimpil/duratom/blob/d08cb821f8d9938df848f38cd700aedab2cfae8f/src/clojure/duratom/core.clj#L112-L119), by wrapping the underlying atom in a lock (and relying on the fact that atom's synchronously block on their watches before returning from `swap!`).

I've also confirmed this behaviour at a REPL: 

```clojure
(def a (db/duratom :local-file :file-path "/tmp/test-duratom.edn" :commit-mode :sync :init 0 ))
(def b (atom []))
(add-watch a :watcher (fn [k ref old new] (swap! b conj [old new])))

(dotimes [n 100000] (future (swap! a inc)))

(apply < (map first @b)) ;; => true
```

The `true` here indicates that all starting (prior to `inc`) states were linearised.

However if you repeat the experiment with a normal `atom` you may witness the out of order behaviour mentioned:

```clojure
(def a (atom 0))
(def b (atom []))
(add-watch a :watcher (fn [k ref old new] (swap! b conj [old new])))

(dotimes [n 100000] (future (swap! a inc)))
(apply < (map first @b)) ;; => false
```

**Comment by kiramclean** [comment]
done with #158
