### ISSUE TITLE
Inject dcterms:modified to all jsonld documents on put

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#72]
Right now we only have series implemented so this issue is just to inject dcterms:modified into those on update. The relevant model code is in `datahost/ldapi/models/series.clj`. Creates should be atomic, i.e. inject the timestamp before the db update is attempted, so either the whole jsonld document (with the modified timestamp) gets inserted or not. This could be implemented in such a way that the code to inject the timestamp could be re-used for other models (we will also be adding the timestamp to e.g. releases and revisions once those are implemented).

This issue is done when all updated series include a `dcterms:modified` key that reflects the time the series was updated.

**Comment by kiramclean** [comment]
It turns out this would be useful now.. one way to detect whether an upsert was an update or create would be to compare the `issued` and `modified` times.. otherwise it's hard to return information from the atomic update/create

**Comment by rosado** [comment]
Shouldn't `modified` be present only on the documents that were actually modified (and not just created)?

**Comment by kiramclean** [comment]
Closed by #114
