### ISSUE TITLE
Inject dcterms:issued to all jsonld documents on first insert

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#73]
Right now we only have series implemented so this issue is just to inject `dcterms:issued` into those on create. The relevant model code is in `datahost/ldapi/models/series.clj`. Creates should be atomic, i.e. inject the timestamp before the db update is attempted, so either the whole jsonld document (with the issued timestamp) gets inserted or not. This could be implemented in such a way that the code to inject the timestamp could be re-used for other models (we will also be adding the timestamp to e.g. releases and revisions once those are implemented).

This issue is done when all new series include a `dcterms:issued` key that reflects the time the series was created.

**Comment by kiramclean** [comment]
Closed by #114
