### ISSUE TITLE
PUT | GET | DELETE Release route

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#75]
Add the route `/data/:series/release/:release-slug` mirroring the patterns established in the series route.

This ticket can be DONE when users can upload a json-ld of release metadata to the route and get it back out again.

Improvements to this area will be made in a future ticket #76 , where we add new representations to this resource for different content-types after the changesets/commits routes/model is complete.

**Comment by kiramclean** [comment]
Should we support updating attributes via query params like on the series endpoint? I guess in this case that would be only `title`?

**Comment by RickMoynihan** [comment]
I think we can argue that `title` and `description` would be useful there yes.

The usecase is basically correcting a typo.  

The idea is that this sort of metadata is mutable; but the core concepts, names, and data aren't.
