### ISSUE TITLE
Implement faceted search properly

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#8]
There are some inconsistencies in the existing faceting behaviour.

We have captured what the new behaviour should be in failing tests in PR #31, and merged them as pending this issue being resolved.  They are flagged with `^:kaocha/pending` metadata so they don't currently break the build, and indicate functionality we've not yet implemented properly.

Some of the inconsisties/issues with faceting are also listed below:

### 1. Enabled status on unconstrained query

[This query](http://localhost:8888/ide?query=%7B%0A%20%20endpoint%20%7B%0A%20%20%20%20catalog(id%3A%20%22http%3A%2F%2Fgss-data.org.uk%2Fcatalog%2Fdatasets%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20catalog_query%20%7B%0A%20%20%20%20%20%20%20%20datasets%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publisher%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20facets%20%7B%0A%20%20%20%20%20%20%20%20%20%20themes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20creators%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20publishers%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A):

```graphql
{
  endpoint {
    catalog(id: "http://gss-data.org.uk/catalog/datasets") {
      id
      catalog_query {
        datasets {
          id
          publisher
        }
        facets {
          themes {
            id
            enabled
          }
          creators {
            id
            enabled
            label
          }
          publishers {
            id
            enabled
          }
        }
      }
    }
  }
}
```
​Says all the facets are `enabled = false`, when I think they should all be `true` (if actually used by the data).

### 2. Locking a single facet value shouldn't disable other selections within that facet

[See this query](http://localhost:8888/ide?query=%7B%0A%20%20endpoint%20%7B%0A%20%20%20%20catalog(id%3A%20%22http%3A%2F%2Fgss-data.org.uk%2Fcatalog%2Fdatasets%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20catalog_query(themes%3A%20%5B%22http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fgdp%23trade%22%5D)%20%7B%0A%20%20%20%20%20%20%20%20datasets%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publisher%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20facets%20%7B%0A%20%20%20%20%20%20%20%20%20%20themes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20creators%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20publishers%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A):

```graphql
{
  endpoint {
    catalog(id: "http://gss-data.org.uk/catalog/datasets") {
      id
      catalog_query(themes: ["http://gss-data.org.uk/def/gdp#trade"]) {
        datasets {
          id
          publisher
        }
        facets {
          themes {
            id
            enabled
          }
          creators {
            id
            enabled
            label
          }
          publishers {
            id
            enabled
          }
        }
      }
    }
  }
}
```

I think in the results for this query many `themes` should be enabled, as most options will expand the amount of query results.  [For example adding the `balanceofpayments` theme to the list](http://localhost:8888/ide?query=%7B%0A%20%20endpoint%20%7B%0A%20%20%20%20catalog(id%3A%20%22http%3A%2F%2Fgss-data.org.uk%2Fcatalog%2Fdatasets%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20catalog_query(themes%3A%20%5B%22http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fgdp%23trade%22%0A%20%20%20%20%20%20%22https%3A%2F%2Fwww.ons.gov.uk%2Feconomy%2Fnationalaccounts%2Fbalanceofpayments%22%5D)%20%7B%0A%20%20%20%20%20%20%20%20datasets%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20publisher%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20facets%20%7B%0A%20%20%20%20%20%20%20%20%20%20themes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20creators%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20publishers%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) results increases the results from ~7 to ~20.

It might be nice to disable options which don't grow the results, though at the minute I don't think that is necessary.

### 3. Locking a single facet value should enable appropriate selections in other facets

So for example in a variant of our [original query](http://localhost:8888/ide?query=%7B%0A%20%20endpoint%20%7B%0A%20%20%20%20catalog(id%3A%20%22http%3A%2F%2Fgss-data.org.uk%2Fcatalog%2Fdatasets%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20catalog_query(themes%3A%5B%22http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fgdp%23trade%22%5D)%20%7B%0A%20%20%20%20%20%20%20%20datasets%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20facets%20%7B%0A%20%20%20%20%20%20%20%20%20%20themes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20publishers%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%09id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A):

```graphql
{
  endpoint {
    catalog(id: "http://gss-data.org.uk/catalog/datasets") {
      id
      catalog_query(themes:["http://gss-data.org.uk/def/gdp#trade"]) {
        datasets {
          id
          label
        }
        facets {
          themes {
            id
          }
          publishers {
            id
            enabled
          }
        }
      }
    }
  }
}
```

 the `publishers` returned shouldn't all be `false`, but should implicitly include as enabled `publishers` who published data into the trade theme, e.g. 

So the above query is inconsistent [with this one](http://localhost:8888/ide?query=%7B%0A%20%20endpoint%20%7B%0A%20%20%20%20catalog(id%3A%20%22http%3A%2F%2Fgss-data.org.uk%2Fcatalog%2Fdatasets%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20catalog_query(%0A%20%20%20%20%20%20%20%20themes%3A%20%5B%22http%3A%2F%2Fgss-data.org.uk%2Fdef%2Fgdp%23trade%22%5D%0A%20%20%20%20%20%20%20%20creators%3A%20%5B%22https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Forganisations%2Fhm-revenue-customs%22%5D%0A%20%20%20%20%20%20)%20%7B%0A%20%20%20%20%20%20%20%20datasets%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20label%0A%20%20%20%20%20%20%20%20%20%20publisher%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20facets%20%7B%0A%20%20%20%20%20%20%20%20%20%20themes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20publishers%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20enabled%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) which locks both `theme = trade` and `creator = hmrc` as it has results.

I think `enabled` is only set to true at the minute if you include that facet in your query... i.e. I think you're thinking of it as whether the checkbox has been ticked; where as I'm thinking of it as being whether you should enable/show or disable/hide that checkbox from the user.

**Comment by RickMoynihan** [comment]
This SPARQL query might be useful as a starting point for this:

```sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?facet ?enabled_val 
WHERE { 

   VALUES (?facet ?facet_val) { 
      (dcterms:publisher UNDEF)
      (dcterms:creator UNDEF) 
      (dcat:theme UNDEF)
   }

   VALUES ?selected_publishers {
#       <https://www.gov.uk/government/organisations/department-for-business-energy-and-industrial-strategy>
       <https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs>
       <https://www.gov.uk/government/organisations/hm-revenue-customs>
#      <https://www.gov.uk/government/organisations/office-for-national-statistics>
 #     UNDEF
   }

   VALUES ?selected_creators {
#     <https://www.gov.uk/government/organisations/department-for-transport>
#      <https://www.gov.uk/government/organisations/office-for-national-statistics>
#      <https://www.gov.uk/government/organisations/department-for-business-energy-and-industrial-strategy>
      UNDEF
   }

   VALUES ?selected_themes {
#      <https://www.ons.gov.uk/economy/governmentpublicsectorandtaxes/researchanddevelopmentexpenditure>
#      <http://gss-data.org.uk/def/gdp#trade>
#      <https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork>
      <http://gss-data.org.uk/def/gdp#climate-change>
#      UNDEF
   }


  ?dsid a dcat:Dataset ; 
        dcterms:publisher ?selected_publishers ;
        dcterms:creator ?selected_creators ; 
        dcat:theme ?selected_themes ;
        ?facet ?enabled_val .
 
 } 
```

**Comment by rosado** [comment]
After reading the original description it wasn't clear to me what the actual problem, let alone what is the solution should be. But after some discussion with @RickMoynihan I arrived at the two problems below. 

_Note: Apologies for using math notation, but it is concise and I think pretty common._

## Problem 1

The query returns compound value `{datasets, facets: Facets}`, where `type Facets = {enabled: bool, ...}`. The "enabled" field is a synthetic field with value set according to the rule below:

```
- D - dataset returned by the query
- Facet[x] - facet x
- Rel(d) - where d ∈ D, all relations of entity d

(Facet[x].enabled == true) ⇔ ∃ d∈D: Facet[x] ∈ Rel(d)
```

At the moment this value is not set correctly.

## Problem 2

The query can be constrained along the "axis" of each facet (at the moment: themes, creators, publishers) by supplying a list of allowed values per facet.

While instinctively it may seem the right behaviour is to make the final dataset an intersection of datasets as if we queried them one by on (e.g. constraining just a single facet value), this is not what we want (and not what user expects).

In short, the expected behaviour is to use
- union operation for constraints within a single facet
- intersection for constraints between different facets

Definitions

```
- F - full dataset (think: what's in the database)
- vals(F, Facet[x]) - set of all values of Facet[x] in F
- lock(x, {v1, v2, ..., vN}) - lock possible values of Facet[x]
  to values of the set {v1, ... vN}
- query_d(F, {lock(x, {v1, ..., vN}), ...}) - dataset items of F, 
  with constraints on facets specified lock(x,{...})
```

Adding a facet value for a particular facet (`Facet[x]`) (e.g. user setting a checkbox value to "checked" within a particular facet)

``` 
query_d(F, {lock(x, {v1, v2, ..., vN} ∪ {vO})}) 
= query_d(F, {lock(x, {v1, v2, ..., vN})}) ∪ query_d(F, {lock(x, {vO})})

// behaviour: constraining values within one facet should expand the result set
query_d(F, {lock(x, {v1, v2, ..., vN})}) ⊆ query_d(F, {lock(x, {v1, v2, ..., vN} ∪ {vO})})
```

Constraining values for different facets (e.g. user setting a checkbox value(s) to "checked" for a facet that hasn't been constrained so far, `y`)

```
query_d(F, query_d(F, {lock(x, {v1, v2, ..., vN}, lock(y, {u1, u2, ..., uM})})) 
= query_d(F, {lock(x, {v1, v2, ..., vN})}) ∩ query_d(F, lock(y, {u1, u2, ..., uM})})

// behaviour: constraining additional facets should narrow down the result set
query_d(F, {lock(x, {v1, v2, ..., vN}, lock(y, {u1, u2, ..., uM})}) ⊆ query_d(F, {lock(x, {v1, v2, ..., vN})})

```
