### ISSUE TITLE
Support multiple representations for `GET .../:release`

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/datahost-prototypes#92]
This route in particular (but also potentially all of them at some point) should support content-negotiation to multiple different representations.

For this route we will need to support linked data dereferencing and content-negotiation for two different representations:

NOTE the two parts may be split into two different tickets.  Th

1. The JSON-LD metadata which should look something like this:

```
{"@id": "/data/life-expectancy/release/1",
  "@type": "datahost:Release"
  "dcterms:title": "2023",
  "rdfs:label": "Life Expectancy : 2023",
  "datahost:changes":[ # todo insert changeset here that contains commits
                       {"@id": "/data/life-expectancy/changesets/1/1",
                       "@type": "datahost:Append"
                       "datahost:append": "/data/life-expectancy/changesets/1/1.csv",
                       "dcterms:description": "Initial load of observations"}]}
```

You would get this when dereferencing like this:

`GET /data/life-expectancy/release/2023 Accept: application/json+ld`

NOTE that the `datahost:changes` key needs to be dynamically `assoc` ed into the provided metadata document for the release.  This should then represent the commit history.  Because of this extra data overlay, this represents an augmentation of the prerequisite issue #75.

2. Users should be able to ask for the data at that revision by derefencing like this:

`GET /data/life-expectancy/release/2023 Accept: text/csv`

This should then result in the CSV being materialised dynamically from the commit history.  In order to do this we should use the triple-store to query all the commit data to assemble the linearised changesets/commits, applying appends and deletes in order (in memory is fine for the prototype).  Delete's should be applied before appends.

You can consult the reagent delta tool prototype code for an example of the algorithm to do this if you are unsure.

## Prerequisites

A prerequisite to both halves of this ticket is #55.  We will want to use the triplestore to assemble metadata for the change log driving both of these tickets.

**Comment by kiramclean** [comment]
Closing, superseded by #119
